### ISSUE TITLE
Weighting UserMeta

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPressLabs#107]
### Describe your question

Hello! 
I have a question about searching for users. I want to find Jon Snow. 
first_name = John
last_name = Snow 
When I fulfill the search for "John Snow", I have 10 people in the results:
1. John Cena
2. John Cleese
3. John Daley
4. John Goodman
5. John Legend
6. John Leguizamo
7. John Mahoney
8. John Mellencamp
9. John Rhys-Davies
10. John Snow 

If the request is only one word "Snow", there is only one line "John Snow" in the search results

The question of how to set Last_name more than first_name?
How to configure weights for other usermeta fields?

Here are my observations on working with user search. The entire user table is indexed, email, login, settings, system fields. This is wrong, you have to manually exclude all fields through a filter, leaving only the necessary ones. It would be logical to do the same as for posts "Manage Search Fields & Weighting", you need an additional field - added. If you want to change the weight - change it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi ws256,

Since the Users feature is available in the ElasticPressLabs plugin, we have transferred your issue to the respective repository. Regarding your question, you can try changing the search algorithm to version 4 and see if it makes any difference. You can do this by adding this snippet. 

```
		 add_filter( 'ep_user_search_algorithm', function( ) {
			return '4.0';
		 } );
```

Or, you can use `ep_user_formatted_args` [filter](https://github.com/10up/ElasticPressLabs/blob/develop/includes/classes/Indexable/User/User.php#L514) to give more weight to the last name.

Since this isn't a bug and no further input is required, I am closing this issue.

Regards,
Burhan
