### ISSUE TITLE
load_textdomain_just_in_time warnings

### ISSUE THREAD

**Issue by kevinlisota** [10up/ElasticPressLabs#109]
### Describe the bug

In WP 6.7, this plugin now kicks off the following Doing It Wrong message on every pageload

Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the elasticpress domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)

### Steps to Reproduce

Active ElasticPress Labs and use Query Monitor on each page load.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
That error is related to the `elasticpress` text domain, not the `elasticpress-labs` domain. It is also worth noting that Query Monitor is _probably_ the problem here, as stated in [this comment](https://github.com/johnbillion/query-monitor/issues/919#issuecomment-2523816277).

EP Labs already calls the `load_plugin_textdomain` function in the `init` hook, so there is nothing to be done on this one.

**Comment by columbian-chris** [comment]
Thanks, @felipeelia.
